export const menuData = {
  BASICS: [
    {
      name: "MARGHERITA (CHEESE)",
      prices: { small: 199, medium: 279, large: 499 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "BASICS",
    },
    {
      name: "CHEESE & TOMATO",
      prices: { small: 189, medium: 279, large: 499 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "BASICS",
    },
    {
      name: "MARGHERITA (CHEESE)",
      prices: { small: 209, medium: 279, large: 499 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "BASICS",
    },
    {
      name: "VEG CHEESE",
      prices: { small: 109, medium: 259, large: 599 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "BASICS",
    },
    {
      name: "MARGHERITA (CHEESE)",
      prices: { small: 199, medium: 279, large: 499 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "BASICS",
    },
    {
      name: "CHEESE & TOMATO",
      prices: { small: 189, medium: 279, large: 499 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "BASICS",
    },
    {
      name: "MARGHERITA (CHEESE)",
      prices: { small: 209, medium: 279, large: 499 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "BASICS",
    },
    {
      name: "VEG CHEESE",
      prices: { small: 109, medium: 259, large: 599 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "BASICS",
    },
  ],
  SPECIALS: [
    {
      name: "MARGHERITA SUPREME",
      prices: { small: 249, medium: 329, large: 519 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "SPECIALS",
    },
    {
      name: "FARM FRESH",
      prices: { small: 259, medium: 339, large: 519 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "SPECIALS",
    },
    {
      name: "TEXAS SPECIAL",
      prices: { small: 269, medium: 339, large: 519 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "SPECIALS",
    },
    {
      name: "MARGHERITA SUPREME",
      prices: { small: 249, medium: 329, large: 519 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "SPECIALS",
    },
    {
      name: "FARM FRESH",
      prices: { small: 259, medium: 339, large: 519 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "SPECIALS",
    },
    {
      name: "TEXAS SPECIAL",
      prices: { small: 269, medium: 339, large: 519 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "SPECIALS",
    },
    {
      name: "MARGHERITA SUPREME",
      prices: { small: 249, medium: 329, large: 519 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "SPECIALS",
    },
    {
      name: "FARM FRESH",
      prices: { small: 259, medium: 339, large: 519 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "SPECIALS",
    },
    {
      name: "TEXAS SPECIAL",
      prices: { small: 269, medium: 339, large: 519 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "SPECIALS",
    },
  ],
  FEASTS: [
    {
      name: "VEGGIE OVERLOAD",
      prices: { small: 309, medium: 519, large: 739 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "FEASTS",
    },
    {
      name: "TANDOORI FEAST",
      prices: { small: 309, medium: 519, large: 739 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "FEASTS",
    },
    {
      name: "CHIPOTLE FEAST",
      prices: { small: 309, medium: 519, large: 739 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "FEASTS",
    },
    {
      name: "VEGGIE OVERLOAD",
      prices: { small: 309, medium: 519, large: 739 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "FEASTS",
    },
    {
      name: "TANDOORI FEAST",
      prices: { small: 309, medium: 519, large: 739 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "FEASTS",
    },
    {
      name: "CHIPOTLE FEAST",
      prices: { small: 309, medium: 519, large: 739 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "FEASTS",
    },
    {
      name: "VEGGIE OVERLOAD",
      prices: { small: 309, medium: 519, large: 739 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "FEASTS",
    },
    {
      name: "TANDOORI FEAST",
      prices: { small: 309, medium: 519, large: 739 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "FEASTS",
    },
    {
      name: "CHIPOTLE FEAST",
      prices: { small: 309, medium: 519, large: 739 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "FEASTS",
    },
  ],
  GOURMET: [
    {
      name: "MEDITERRANEAN DELIGHTS",
      prices: { small: 419, medium: 559, large: 759 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "GOURMET",
    },
    {
      name: "REAL PESTO & BASIL",
      prices: { small: 419, medium: 559, large: 759 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "GOURMET",
    },
    {
      name: "7-CHEESE PIZZA",
      prices: { small: 419, medium: 559, large: 759 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "GOURMET",
    },
    {
      name: "MEDITERRANEAN DELIGHTS",
      prices: { small: 419, medium: 559, large: 759 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "GOURMET",
    },
    {
      name: "REAL PESTO & BASIL",
      prices: { small: 419, medium: 559, large: 759 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "GOURMET",
    },
    {
      name: "7-CHEESE PIZZA",
      prices: { small: 419, medium: 559, large: 759 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "GOURMET",
    },
  ],
  SIDES: [
    {
      name: "GARLIC STICKS (STUFFED)",
      prices: { small: 209 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "SIDES",
    },
    {
      name: "GARLIC STICKS",
      prices: { small: 149 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "SIDES",
    },
    {
      name: "TOMATO SOUP",
      prices: { small: 99 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "SIDES",
    },
  ],
  PASTAS: [
    {
      name: "ALFREDO PASTA",
      prices: { small: 199 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "PASTAS",
    },
    {
      name: "ARRABIATA PASTA",
      prices: { small: 199 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "PASTAS",
    },
    {
      name: "PESTO PASTA",
      prices: { small: 199 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "PASTAS",
    },
    {
      name: "ALFREDO PASTA",
      prices: { small: 199 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "PASTAS",
    },
    {
      name: "ARRABIATA PASTA",
      prices: { small: 199 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "PASTAS",
    },
    {
      name: "PESTO PASTA",
      prices: { small: 199 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "PASTAS",
    },
    {
      name: "ALFREDO PASTA",
      prices: { small: 199 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "PASTAS",
    },
    {
      name: "ARRABIATA PASTA",
      prices: { small: 199 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "PASTAS",
    },
    {
      name: "PESTO PASTA",
      prices: { small: 199 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "PASTAS",
    },
  ],
  DRINKS: [
    {
      name: "LEMONADE",
      prices: { small: 99 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DRINKS",
    },
    {
      name: "PINK LEMONADE",
      prices: { small: 99 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DRINKS",
    },
    {
      name: "COLD DRINK",
      prices: { small: 89 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DRINKS",
    },
    {
      name: "LEMONADE",
      prices: { small: 99 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DRINKS",
    },
    {
      name: "PINK LEMONADE",
      prices: { small: 99 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DRINKS",
    },
    {
      name: "COLD DRINK",
      prices: { small: 89 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DRINKS",
    },
  ],
  DESSERTS: [
    {
      name: "COOKIES & ICE CREAM",
      prices: { small: 175 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DESSERTS",
    },
    {
      name: "CHOCOLATE PAN PIZZA",
      prices: { small: 275 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DESSERTS",
    },
    {
      name: "COOKIES & ICE CREAM",
      prices: { small: 175 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DESSERTS",
    },
    {
      name: "CHOCOLATE PAN PIZZA",
      prices: { small: 275 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DESSERTS",
    },
    {
      name: "COOKIES & ICE CREAM",
      prices: { small: 175 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DESSERTS",
    },
    {
      name: "CHOCOLATE PAN PIZZA",
      prices: { small: 275 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DESSERTS",
    },
    {
      name: "COOKIES & ICE CREAM",
      prices: { small: 175 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DESSERTS",
    },
    {
      name: "CHOCOLATE PAN PIZZA",
      prices: { small: 275 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DESSERTS",
    },
  ],
  DEALS: [
    {
      name: "FAMILY COMBO",
      prices: { small: 999 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DEALS",
    },
    {
      name: "PARTY PACK",
      prices: { small: 1499 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DEALS",
    },
    {
      name: "WEEKEND SPECIAL",
      prices: { small: 799 },
      image: "https://res.cloudinary.com/dnkfvkyre/image/upload/v1747202665/item_images/xkfzmqpzayofb1hwmi79.png",
      category: "DEALS",
    },
  ],
};
