import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Barlow_Condensed,
  Nunito_Sans,
  Aclonica,
  Roboto,
  Roboto_Flex,
  Antonio,
  Barlow,
  Abhaya_Libre,
} from "next/font/google";
import "./globals.css";

// Google fonts as variables (all subsets: "latin" by default)
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const barlowCondensed = Barlow_Condensed({ weight: ["500", "600", "700"], variable: "--font-barlow-condensed", subsets: ["latin"] });
const nunitoSans = Nunito_Sans({ weight: ["400", "600"], variable: "--font-nunito-sans", subsets: ["latin"] });
const aclonica = Aclonica({ weight: "400", variable: "--font-aclonica", subsets: ["latin"] });
const roboto = Roboto({ weight: "900", variable: "--font-roboto", subsets: ["latin"] });
const robotoFlex = Roboto_Flex({ weight: "800", variable: "--font-roboto-flex", subsets: ["latin"] });
const antonio = Antonio({ weight: ["300", "700"], variable: "--font-antonio", subsets: ["latin"] });
const barlow = Barlow({ weight: "400", variable: "--font-barlow", subsets: ["latin"] });
const abhayaLibre = Abhaya_Libre({ weight: ["400", "700"], variable: "--font-abhaya-libre", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${barlowCondensed.variable}
          ${nunitoSans.variable}
          ${aclonica.variable}
          ${roboto.variable}
          ${robotoFlex.variable}
          ${antonio.variable}
          ${barlow.variable}
          ${abhayaLibre.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
